### PR TITLE
Transform `mountpoint` into an array of objects called `mountpoints`

### PR DESCRIPTION
**Pull request by jviotti**
See: https://github.com/resin-io-modules/drivelist/issues/98
Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

### CODE REVIEW

**Comment by lurch** [comment]
:+1: :+1:

**Comment by lurch** [comment]
Strictly speaking, this is only the first step to fixing #98, it doesn't fix it entirely ;)

**Comment by jviotti** [comment]
Yeah, fair enough. I've changed `Fixes:` to `See:`.

**Comment by jviotti** [comment]
Lets get this PR merged and released so we can unblock ourselves in https://github.com/resin-io/etcher/issues/830, and lets keep discussing how to make it better in https://github.com/resin-io-modules/drivelist/issues/98

**Pull request merged**
