### PR TITLE
refactor: Optimise linux.sh script

### PR DESCRIPTION
**Pull request by lurch**
By using some bash scripting tricks, it now only executes a single `lsblk` command per disk, rather than 4 `lsblk` commands per disk.
It produces **identical** output to before, and also still works fine with there being spaces in the 'MODEL' string.

### CODE REVIEW

**Comment by jviotti** [comment]
Perfect! Thanks a lot!

**Comment by jviotti** [comment]
@lurch The drive descriptions look very weird here (Ubuntu 16.04 x64) after this patch:

screenshot from 2016-11-01 15-14-31

**Comment by jviotti** [comment]
The `size` also seems to be showing the whole `lsblk` output rather than just the size column:

```sh
size: 68719476736  0  0 Ubuntu 16.04 x86
```

**Comment by jviotti** [comment]
Replacing `${diskinfo[N]}` with `$(echo $diskinfo | awk '{ print $N+1 }')` seems to make it better.

**Comment by jviotti** [comment]
This works fine for me:

```diff
diff --git a/scripts/linux.sh b/scripts/linux.sh
index f0ac8e5..522ff03 100755
--- a/scripts/linux.sh
+++ b/scripts/linux.sh
@@ -23,10 +23,10 @@ for disk in $DISKS; do
 
   device="/dev/$disk"
   diskinfo="$(lsblk -b -d $device --output SIZE,RO,RM,MODEL | ignore_first_line)"
-  size=${diskinfo[0]}
-  protected=${diskinfo[1]}
-  removable=${diskinfo[2]}
-  description=${diskinfo[@]:3}
+  size=$(echo $diskinfo | awk '{ print $1 }')
+  protected=$(echo $diskinfo | awk '{ print $2 }')
+  removable=$(echo $diskinfo | awk '{ print $3 }')
+  description=$(echo $diskinfo | awk '{ $1=$2=$3=""; print substr($0, 4) }')
   description="\"${description//"/\\"}\""
   mountpoint=`get_mountpoint $device`
```

**Comment by jviotti** [comment]
I'll merge the fix I proposed above to prevent `master` from being in a bad state, but feel free to send another PR that doesn't use `awk` if you want!

**Comment by lurch** [comment]
Huh, it worked fine for me on Ubuntu 14.04 :-S
Apologies for accidentally breaking master! :(

**Comment by lurch** [comment]
Arrrgghhh, mea culpa! When copying my changes into GitHub, I forgot to change a couple of double-quotes to parentheses! Whoops. https://github.com/resin-io-modules/drivelist/compare/b850930...lurch:patch-1

#112 should fix things again?

**Comment by jviotti** [comment]
@lurch The new commit works great! I'll merge!

**Pull request merged**
