### PR TITLE
feat(drivelist): Implement native bindings

### PR DESCRIPTION
**Pull request by jhermsmeier**
**NOTE:** This is a **work-in-progress**

**Changes:**

- Removed scripts
- Removed obsolete dependencies
- Removed obsolete `lib/` code
- Added native methods for Win, Linux & Darwin
- Moved `example.js` to `example/index.js`
- Made example output colored (if stdout is a TTY)
- Updated `.gitignore` to ignore the `build` directory completely
- Updated `.npmignore` with examples, build artifacts and `.yml` files

**TODO:**

- [ ] Update & adjust tests
- [ ] Support for all major operating systems:
  - [ ] Mac OS
  - [ ] Windows
  - [ ] Linux
- [ ] Implement object packing of `MountPoint` structs
- [ ] Add `cpplint` to CI services
- [ ] Update `doc/README.hbs`

**Follow-up Work:**
- Add prebuilds

Change-Type: major

### CODE REVIEW

**Comment by jviotti** [comment]
@jhermsmeier Do you think we can make this PR only use native code for Windows? I'd like to push and merge my Windows changes, without having to wait for native code for the other OSes.

**Comment by jhermsmeier** [comment]
@jviotti yeah, can do - probably would make sense for me to split this up into a commit for each change, and cherry pick the windows only parts into a new PR?

**Comment by jviotti** [comment]
Yeah, that'd be awesome :+1:

**Comment by jhermsmeier** [comment]
@jviotti split everything up now, and pushed the relevant commits to build the windows-only native support to the `native-windows` branch: https://github.com/resin-io-modules/drivelist/tree/native-windows

Note that the commits in here and there now ideally shouldn't be squashed anymore, as that'd mangle the hashes.

**Comment by jhermsmeier** [comment]
Closing this, as it's been superseded by https://github.com/resin-io-modules/drivelist/pull/178

**Pull request closed without merging**
