### PR TITLE
fix(darwin): Allow mountpoints containing space characters

### LINKED ISSUE #245: Mountpoint path problem in Mac OS X
#154 is not currently fixed, as you can see from output i get:

```
"enumerator": "diskutil",
"busType": "UNKNOWN",
"busVersion": "0.0",
"device": "/dev/disk5",
"raw": "/dev/rdisk5",
"description": "LaCie RAID - ST2000DM001-9YN164",
"error": null,
"size": 2000054943744,
"blockSize": null,
"logicalBlockSize": null,
"mountpoints": [{
        "path": "/Volumes/LaCie"
    }
],
"isReadOnly": false,
"isSystem": true,
"isVirtual": null,
"isRemovable": null,
"isCard": null,
"isSCSI": null,
"isUSB": null,
"isUAS": null
```

description is correct: LaCie RAID
mountpoint path break at whitespace, should be `"path": "/Volumes/LaCie RAID"`

### PR DESCRIPTION
**Pull request by lurch**
Fixes #245
Change-Type: patch

I **think** this should work, but I need somebody who has a Mac (@jviotti ? @jhermsmeier  ? ) to check that it actually _does_ fix #245

### CODE REVIEW

**Comment by jhermsmeier** [comment]
This correctly enumerates mountpoints with spaces now:

```js
{
  enumerator: 'diskutil',
  busType: 'UNKNOWN',
  busVersion: '0.0',
  device: '/dev/disk2',
  raw: '/dev/rdisk2',
  description: 'SD Card Reader',
  error: null,
  size: 31104958464,
  blockSize: null,
  logicalBlockSize: null,
  mountpoints: [ { path: '/Volumes/Patchwork 3.8.5' } ],
  isReadOnly: false,
  isSystem: false,
  isVirtual: null,
  isRemovable: null,
  isCard: null,
  isSCSI: null,
  isUSB: null,
  isUAS: null
}
```

**Comment by lurch** [comment]
@jhermsmeier Does OSX also allow mountpoints with any of the weird characters I fixed for Linux in #156 ?  If you have time, could you see if this patch also works with any / all of those?

**Comment by lurch** [comment]
^ re-ping @jhermsmeier @jviotti

**Comment by lurch** [comment]
Apologies - looks like myself and @jhermsmeier added the ready-to-merge label at the same time!

**Pull request merged**
