### PR TITLE
Vendoring of lodash to reduce module size

### PR DESCRIPTION
**Pull request by robinwassen**
This to reduce the production size of the drivelist module.

See #215

### CODE REVIEW

**Comment by Page-** [comment]
Hey, the problem of this PR it that it will actually increase the size of the drivelist module for any case where another dependency also depends on lodash as npm will not be able to dedupe lodash and so the cost will have to be paid for every module that depends on lodash.  It would be much better to use something like https://webpack.js.org/ in the end product in order to remove unused code/files, minify code, and also consolidate shared dependencies

**Comment by robinwassen** [comment]
@Page- I hear you, but does webpack actually strip unused code? Otherwise an effort is needed to use the modularized lodash functions in order for that to work, that also voids the argument of deduping since that will also cause duping.

**Comment by jhermsmeier** [comment]
Webpack will not work with this, as drivelist has native bindings (also, Webpack shouldn't be used to preprocess npm packages' contents) – the best solution here would be to just install the individual lodash components (every component is also [published separately on npm](https://npms.io/search?q=lodash)), which will let npm dedupe it properly while only using the necessary parts.

**Comment by robinwassen** [comment]
@jhermsmeier I will give that a shot and see if it gives a positive result.

Closing this PR and creating a new one for that.

**Comment by jhermsmeier** [comment]
Sweet, thanks!

**Comment by Page-** [comment]
@jhermsmeier it's perfectly possible to use webpack to minify npm packages, but you're right that you need to handle native dependencies separately, by marking them as "external" so that they are still loaded via node_modules (https://github.com/resin-io/resin-supervisor/ uses webpack for minification and has native modules)

**Pull request closed without merging**
