### PR TITLE
feat(lib): Use lsblk directly, parse json output

### PR DESCRIPTION
**Pull request by jhermsmeier**
This switches from using a bash script on linux to shelling out
to `lsblk` directly, using its `--json` option to obtain & parse
machine-readable output – removing the need for external script
files entirely.

**NOTE:** This branch is based on `diskutil-plist`, which has hence has been selected as merge-base. This will automatically resolve to `master` once #253 is merged.

Change-Type: minor
Depends on: #253 
Connects To: #231, https://github.com/resin-io-modules/drivelist/issues/165

### CODE REVIEW

**Comment by lurch** [comment]
> removing the need for external script files entirely.

I guess the stuff in the README about external scripts & yaml needs to be updated then? :wink:

**Comment by jhermsmeier** [comment]
Huh? This was unexpected...

**Comment by Shou** [comment]
Yeah, that is weird, I was in the middle of reviewing too...

**Comment by jhermsmeier** [comment]
I'll rebase and open a new PR; needs some more work from what it looks like anyways, as it blew on the Linux boxes on Travis – maybe `--json` isn't supported on older versions of `lsblk`? Didn't find much info as to feature history, but was apparently added in 2015.

**Comment by Shou** [comment]
Here are my comments anyway :)

**Comment by lurch** [comment]
> but was apparently added in 2015.

...which means it probably won't work on the Ubuntu 12.04 that I think Etcher still supports? :-/

**Comment by jhermsmeier** [comment]
@lurch yeah, also didn't work on Travis at all – see #255, which also adds parsing the "old" `--pairs` output.

**Pull request closed without merging**
