### PR TITLE
feat(windows): print error code string description in case of errors

### PR DESCRIPTION
**Pull request by jviotti**
Change-Type: minor
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by jviotti** [comment]
Fixed!

**Comment by jviotti** [comment]
@hedss @lekkas I don't know what's going on, but VersionBot is not working on this repo anymore :(

**Comment by hedss** [comment]
@jviotti The release tag for `5.0.25` isn't valid, it should be `v5.0.25` so `versionist` can't find the reference. I guess it was added manually.

**Comment by jviotti** [comment]
@hedss I see, I always seem to get the `v` prefix wrong :P Could we make VersionBot print a more descriptive error message, or maybe even a warning, but still make it cope with the lack of the `v`?

**Comment by lurch** [comment]
I think if we used VersionBot 100%, and never merged manually, then we'd never get invalid tags?

**Comment by jviotti** [comment]
True. I went for manual merges given that we needed to keep moving, and I didn't know how to fix it.

**Comment by hedss** [comment]
It's a fair comment. Ideally `versionist` needs to be libraried so we can can use it and get better error messages out. Unfortunately I've had zero time to do this. :-(

**Pull request merged**
